function [scenario, egoVehicle] = DrivingScenarioDesigner_points_MPC()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 18-Dec-2020 02:06:44

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [6 1 0;
    127 4 0];
laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [10.6 -0.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [10.6 -0.9 0;
    23.5 -0.2 0;
    34 0.8 0;
    44.1 2.2 0;
    57.3 2.5 0;
    74.8 3.5 0;
    87.7 3.5 0;
    94.8 2.9 0;
    106.3 3.5 0;
    117.1 4.2 0;
    124.2 4.5 0;
    124.5 4.9 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

